source 'https://rubygems.org'

gem 'rails', '5.2.8'
gem 'tzinfo-data' #needed by windows
gem 'mysql2'
gem 'mongoid'
gem 'mongo'
gem 'execjs'
#gem 'libv8'
gem 'mobvious'
gem 'formtastic'
#gem 'therubyracer', platforms: :ruby # avoid loading on windows
gem 'airbrake'
#  gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby'
gem 'bcrypt'
gem 'text'
gem 'json'
gem 'pry'
gem 'pry-byebug'
gem 'email_veracity'
gem 'unicode'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'gretel'
gem 'geocoder', '1.3.7' #appears to be a regression in 1.4
gem 'bourbon'
gem 'mail-logger'
gem 'devise'
gem 'devise-encryptable'
gem 'nokogiri', ">= 1.13.6"
#gem 'osgb', git: 'https://github.com/FreeUKGen/osgb.git'
gem 'rubyzip'
gem 'zip-zip'
gem 'rspec-rails'
gem 'carrierwave-mongoid', '1.2.0', require: 'carrierwave/mongoid'
gem 'simple_form'
gem 'newrelic_rpm'
gem 'octokit'
gem 'traceroute'
gem 'sass-rails' #,   '~> 3.2.3'
gem 'coffee-rails'#, '~> 3.2.1'
gem 'uglifier'#, '>= 1.0.3'
gem 'jquery-rails'
gem 'font_awesome5_rails'
gem 'rubocop-rails'
gem 'rubocop', '~> 1.23.0', require: false
gem 'browser'
gem 'rails3-jquery-autocomplete'
gem 'jquery-validation-rails', '~> 1.13', '>= 1.13.1'
gem 'rails_autolink'
gem 'mongoid-grid_fs'
gem 'bootstrap_form'
