source 'https://rubygems.org'

gem 'rails'
gem 'tzinfo-data' #needed by windows
gem 'mysql2'
gem 'refinerycms'
gem 'refinerycms-authentication-devise'
gem 'refinerycms-wymeditor'
gem 'mongoid'
gem 'mongo'
gem 'execjs'
gem 'libv8'
gem 'mobvious'
gem 'formtastic'
gem 'therubyracer', platforms: :ruby # avoid loading on windows
gem 'airbrake'
gem 'bcrypt', platforms: :ruby  # avoid loading on windows
gem 'text'
gem 'json'
gem 'pry'
gem 'pry-byebug'
gem 'email_veracity'
gem 'unicode'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'gretel'
gem 'geocoder', '1.3.7' #appears to be a regression in 1.4
gem 'bourbon'
gem 'mail-logger'
gem 'devise'
gem 'devise-encryptable'
gem 'nokogiri'
gem 'osgb', git: 'https://github.com/FreeUKGen/osgb.git'
gem 'rubyzip'
gem 'zip-zip'
gem 'rspec-rails'
gem 'fog'
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'simple_form'
gem 'newrelic_rpm'
gem 'octokit'
gem 'traceroute'
gem 'sass-rails' #,   '~> 3.2.3'
gem 'coffee-rails'#, '~> 3.2.1'
gem 'uglifier'#, '>= 1.0.3'
gem 'jquery-rails'
gem 'refinerycms-county_pages', :path => 'vendor/extensions'
