development:
  mongodb_bin_location: #location of the mongodb binaries eg 'd:/mongodb/bin/'
  datafiles: #location of the FR user files eg 'c:/freereg11/'
  website: # the website being used eg '192.168.1.112:3000'
  backup_directory: #location of the backup folder 'd:/users/kirk/documents/github/myopicvicar/tmp/backups'
  sleep: # number of seconds to wait after each entry/search_record creation/deletion  eg '0.001'
  emmendation_sleep:
  datafiles_changeset: # location of the FR1 user files eg 'c:/freereg12/' ! obsolete
  datafiles_delta: # location of the file that holds the FR1 rsync list eg'm:/freereg1.delta'
  files_for_processing: # location of file to hold list of files for overnight processing eg 'm:/processing.delta'
  delete_list: #location of a file to hold the list of files for overnight deletion of entries and search records eg 'm:/delete_list.txt'
  member_open: # a value of true means system is open for login; false it is under maintenance. SA and technical can still login
  ucf_support: # true of false for wildcard UI
  witness_support: # true of false for witness UI
  github_issues_login: #login for issues
  github_issues_password: #password for issues
  github_issues_repo: #as stated
  days_to_retain_search_queries: #as stated
  max_search_time: #as stated
  our_secret_key: #password secret key
  secret_key_base: #secrets secret key base
  timeout_researcher: 120
  timeout_transcriber: 60
  timeout_manager: 240


test:
  mongodb_bin_location: 
  datafiles: 
  website: 
  backup_directory: 
  sleep:
  datafiles_changeset:
  datafiles_delta: 
  files_for_processing: 
  delete_list: 
  member_open: 
  max_search_time: #as stated
  our_secret_key: #password secret key
  secret_key_base: #secrets secret key base

production:
  mongodb_bin_location: 
  datafiles: 
  website: 
  backup_directory:
  sleep: 
  emmendation_sleep:
  datafiles_changeset:
  datafiles_delta: 
  files_for_processing: 
  delete_list: 
  member_open:
  ucf_support: 
  github_issues_login: 
  github_issues_password: 
  github_issues_repo:
  days_to_retain_search_queries: 
  max_search_time: #as stated
  our_secret_key: #password secret key
  secret_key_base: #secrets secret key base
  timeout_researcher: 120
  timeout_transcriber: 60
  timeout_manager: 240
