require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChurchNamesController do

  # This should return the minimal set of attributes required to create a valid
  # ChurchName. As you add validations to ChurchName, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChurchNamesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all church_names as @church_names" do
      church_name = ChurchName.create! valid_attributes
      get :index, {}, valid_session
      assigns(:church_names).should eq([church_name])
    end
  end

  describe "GET show" do
    it "assigns the requested church_name as @church_name" do
      church_name = ChurchName.create! valid_attributes
      get :show, {:id => church_name.to_param}, valid_session
      assigns(:church_name).should eq(church_name)
    end
  end

  describe "GET new" do
    it "assigns a new church_name as @church_name" do
      get :new, {}, valid_session
      assigns(:church_name).should be_a_new(ChurchName)
    end
  end

  describe "GET edit" do
    it "assigns the requested church_name as @church_name" do
      church_name = ChurchName.create! valid_attributes
      get :edit, {:id => church_name.to_param}, valid_session
      assigns(:church_name).should eq(church_name)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChurchName" do
        expect {
          post :create, {:church_name => valid_attributes}, valid_session
        }.to change(ChurchName, :count).by(1)
      end

      it "assigns a newly created church_name as @church_name" do
        post :create, {:church_name => valid_attributes}, valid_session
        assigns(:church_name).should be_a(ChurchName)
        assigns(:church_name).should be_persisted
      end

      it "redirects to the created church_name" do
        post :create, {:church_name => valid_attributes}, valid_session
        response.should redirect_to(ChurchName.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved church_name as @church_name" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChurchName.any_instance.stub(:save).and_return(false)
        post :create, {:church_name => {}}, valid_session
        assigns(:church_name).should be_a_new(ChurchName)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChurchName.any_instance.stub(:save).and_return(false)
        post :create, {:church_name => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested church_name" do
        church_name = ChurchName.create! valid_attributes
        # Assuming there are no other church_names in the database, this
        # specifies that the ChurchName created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChurchName.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => church_name.to_param, :church_name => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested church_name as @church_name" do
        church_name = ChurchName.create! valid_attributes
        put :update, {:id => church_name.to_param, :church_name => valid_attributes}, valid_session
        assigns(:church_name).should eq(church_name)
      end

      it "redirects to the church_name" do
        church_name = ChurchName.create! valid_attributes
        put :update, {:id => church_name.to_param, :church_name => valid_attributes}, valid_session
        response.should redirect_to(church_name)
      end
    end

    describe "with invalid params" do
      it "assigns the church_name as @church_name" do
        church_name = ChurchName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChurchName.any_instance.stub(:save).and_return(false)
        put :update, {:id => church_name.to_param, :church_name => {}}, valid_session
        assigns(:church_name).should eq(church_name)
      end

      it "re-renders the 'edit' template" do
        church_name = ChurchName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChurchName.any_instance.stub(:save).and_return(false)
        put :update, {:id => church_name.to_param, :church_name => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested church_name" do
      church_name = ChurchName.create! valid_attributes
      expect {
        delete :destroy, {:id => church_name.to_param}, valid_session
      }.to change(ChurchName, :count).by(-1)
    end

    it "redirects to the church_names list" do
      church_name = ChurchName.create! valid_attributes
      delete :destroy, {:id => church_name.to_param}, valid_session
      response.should redirect_to(church_names_url)
    end
  end

end
