require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Freereg1CsvEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # Freereg1CsvEntry. As you add validations to Freereg1CsvEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Freereg1CsvEntriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all freereg1_csv_entries as @freereg1_csv_entries" do
      freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:freereg1_csv_entries).should eq([freereg1_csv_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested freereg1_csv_entry as @freereg1_csv_entry" do
      freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
      get :show, {:id => freereg1_csv_entry.to_param}, valid_session
      assigns(:freereg1_csv_entry).should eq(freereg1_csv_entry)
    end
  end

  describe "GET new" do
    it "assigns a new freereg1_csv_entry as @freereg1_csv_entry" do
      get :new, {}, valid_session
      assigns(:freereg1_csv_entry).should be_a_new(Freereg1CsvEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested freereg1_csv_entry as @freereg1_csv_entry" do
      freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
      get :edit, {:id => freereg1_csv_entry.to_param}, valid_session
      assigns(:freereg1_csv_entry).should eq(freereg1_csv_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Freereg1CsvEntry" do
        expect {
          post :create, {:freereg1_csv_entry => valid_attributes}, valid_session
        }.to change(Freereg1CsvEntry, :count).by(1)
      end

      it "assigns a newly created freereg1_csv_entry as @freereg1_csv_entry" do
        post :create, {:freereg1_csv_entry => valid_attributes}, valid_session
        assigns(:freereg1_csv_entry).should be_a(Freereg1CsvEntry)
        assigns(:freereg1_csv_entry).should be_persisted
      end

      it "redirects to the created freereg1_csv_entry" do
        post :create, {:freereg1_csv_entry => valid_attributes}, valid_session
        response.should redirect_to(Freereg1CsvEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved freereg1_csv_entry as @freereg1_csv_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Freereg1CsvEntry.any_instance.stub(:save).and_return(false)
        post :create, {:freereg1_csv_entry => {}}, valid_session
        assigns(:freereg1_csv_entry).should be_a_new(Freereg1CsvEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Freereg1CsvEntry.any_instance.stub(:save).and_return(false)
        post :create, {:freereg1_csv_entry => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested freereg1_csv_entry" do
        freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
        # Assuming there are no other freereg1_csv_entries in the database, this
        # specifies that the Freereg1CsvEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Freereg1CsvEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => freereg1_csv_entry.to_param, :freereg1_csv_entry => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested freereg1_csv_entry as @freereg1_csv_entry" do
        freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
        put :update, {:id => freereg1_csv_entry.to_param, :freereg1_csv_entry => valid_attributes}, valid_session
        assigns(:freereg1_csv_entry).should eq(freereg1_csv_entry)
      end

      it "redirects to the freereg1_csv_entry" do
        freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
        put :update, {:id => freereg1_csv_entry.to_param, :freereg1_csv_entry => valid_attributes}, valid_session
        response.should redirect_to(freereg1_csv_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the freereg1_csv_entry as @freereg1_csv_entry" do
        freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Freereg1CsvEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => freereg1_csv_entry.to_param, :freereg1_csv_entry => {}}, valid_session
        assigns(:freereg1_csv_entry).should eq(freereg1_csv_entry)
      end

      it "re-renders the 'edit' template" do
        freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Freereg1CsvEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => freereg1_csv_entry.to_param, :freereg1_csv_entry => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested freereg1_csv_entry" do
      freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => freereg1_csv_entry.to_param}, valid_session
      }.to change(Freereg1CsvEntry, :count).by(-1)
    end

    it "redirects to the freereg1_csv_entries list" do
      freereg1_csv_entry = Freereg1CsvEntry.create! valid_attributes
      delete :destroy, {:id => freereg1_csv_entry.to_param}, valid_session
      response.should redirect_to(freereg1_csv_entries_url)
    end
  end

end
