require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FreecenDwellingsController do

  # This should return the minimal set of attributes required to create a valid
  # FreecenDwelling. As you add validations to FreecenDwelling, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "entry_number" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FreecenDwellingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all freecen_dwellings as @freecen_dwellings" do
      freecen_dwelling = FreecenDwelling.create! valid_attributes
      get :index, {}, valid_session
      assigns(:freecen_dwellings).should eq([freecen_dwelling])
    end
  end

  describe "GET show" do
    it "assigns the requested freecen_dwelling as @freecen_dwelling" do
      freecen_dwelling = FreecenDwelling.create! valid_attributes
      get :show, {:id => freecen_dwelling.to_param}, valid_session
      assigns(:freecen_dwelling).should eq(freecen_dwelling)
    end
  end

  describe "GET new" do
    it "assigns a new freecen_dwelling as @freecen_dwelling" do
      get :new, {}, valid_session
      assigns(:freecen_dwelling).should be_a_new(FreecenDwelling)
    end
  end

  describe "GET edit" do
    it "assigns the requested freecen_dwelling as @freecen_dwelling" do
      freecen_dwelling = FreecenDwelling.create! valid_attributes
      get :edit, {:id => freecen_dwelling.to_param}, valid_session
      assigns(:freecen_dwelling).should eq(freecen_dwelling)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FreecenDwelling" do
        expect {
          post :create, {:freecen_dwelling => valid_attributes}, valid_session
        }.to change(FreecenDwelling, :count).by(1)
      end

      it "assigns a newly created freecen_dwelling as @freecen_dwelling" do
        post :create, {:freecen_dwelling => valid_attributes}, valid_session
        assigns(:freecen_dwelling).should be_a(FreecenDwelling)
        assigns(:freecen_dwelling).should be_persisted
      end

      it "redirects to the created freecen_dwelling" do
        post :create, {:freecen_dwelling => valid_attributes}, valid_session
        response.should redirect_to(FreecenDwelling.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved freecen_dwelling as @freecen_dwelling" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreecenDwelling.any_instance.stub(:save).and_return(false)
        post :create, {:freecen_dwelling => { "entry_number" => "invalid value" }}, valid_session
        assigns(:freecen_dwelling).should be_a_new(FreecenDwelling)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreecenDwelling.any_instance.stub(:save).and_return(false)
        post :create, {:freecen_dwelling => { "entry_number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested freecen_dwelling" do
        freecen_dwelling = FreecenDwelling.create! valid_attributes
        # Assuming there are no other freecen_dwellings in the database, this
        # specifies that the FreecenDwelling created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FreecenDwelling.any_instance.should_receive(:update_attributes).with({ "entry_number" => "1" })
        put :update, {:id => freecen_dwelling.to_param, :freecen_dwelling => { "entry_number" => "1" }}, valid_session
      end

      it "assigns the requested freecen_dwelling as @freecen_dwelling" do
        freecen_dwelling = FreecenDwelling.create! valid_attributes
        put :update, {:id => freecen_dwelling.to_param, :freecen_dwelling => valid_attributes}, valid_session
        assigns(:freecen_dwelling).should eq(freecen_dwelling)
      end

      it "redirects to the freecen_dwelling" do
        freecen_dwelling = FreecenDwelling.create! valid_attributes
        put :update, {:id => freecen_dwelling.to_param, :freecen_dwelling => valid_attributes}, valid_session
        response.should redirect_to(freecen_dwelling)
      end
    end

    describe "with invalid params" do
      it "assigns the freecen_dwelling as @freecen_dwelling" do
        freecen_dwelling = FreecenDwelling.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreecenDwelling.any_instance.stub(:save).and_return(false)
        put :update, {:id => freecen_dwelling.to_param, :freecen_dwelling => { "entry_number" => "invalid value" }}, valid_session
        assigns(:freecen_dwelling).should eq(freecen_dwelling)
      end

      it "re-renders the 'edit' template" do
        freecen_dwelling = FreecenDwelling.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreecenDwelling.any_instance.stub(:save).and_return(false)
        put :update, {:id => freecen_dwelling.to_param, :freecen_dwelling => { "entry_number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested freecen_dwelling" do
      freecen_dwelling = FreecenDwelling.create! valid_attributes
      expect {
        delete :destroy, {:id => freecen_dwelling.to_param}, valid_session
      }.to change(FreecenDwelling, :count).by(-1)
    end

    it "redirects to the freecen_dwellings list" do
      freecen_dwelling = FreecenDwelling.create! valid_attributes
      delete :destroy, {:id => freecen_dwelling.to_param}, valid_session
      response.should redirect_to(freecen_dwellings_url)
    end
  end

end
