require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Freecen1VldFilesController do

  # This should return the minimal set of attributes required to create a valid
  # Freecen1VldFile. As you add validations to Freecen1VldFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "file_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Freecen1VldFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all freecen1_vld_files as @freecen1_vld_files" do
      freecen1_vld_file = Freecen1VldFile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:freecen1_vld_files).should eq([freecen1_vld_file])
    end
  end

  describe "GET show" do
    it "assigns the requested freecen1_vld_file as @freecen1_vld_file" do
      freecen1_vld_file = Freecen1VldFile.create! valid_attributes
      get :show, {:id => freecen1_vld_file.to_param}, valid_session
      assigns(:freecen1_vld_file).should eq(freecen1_vld_file)
    end
  end

  describe "GET new" do
    it "assigns a new freecen1_vld_file as @freecen1_vld_file" do
      get :new, {}, valid_session
      assigns(:freecen1_vld_file).should be_a_new(Freecen1VldFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested freecen1_vld_file as @freecen1_vld_file" do
      freecen1_vld_file = Freecen1VldFile.create! valid_attributes
      get :edit, {:id => freecen1_vld_file.to_param}, valid_session
      assigns(:freecen1_vld_file).should eq(freecen1_vld_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Freecen1VldFile" do
        expect {
          post :create, {:freecen1_vld_file => valid_attributes}, valid_session
        }.to change(Freecen1VldFile, :count).by(1)
      end

      it "assigns a newly created freecen1_vld_file as @freecen1_vld_file" do
        post :create, {:freecen1_vld_file => valid_attributes}, valid_session
        assigns(:freecen1_vld_file).should be_a(Freecen1VldFile)
        assigns(:freecen1_vld_file).should be_persisted
      end

      it "redirects to the created freecen1_vld_file" do
        post :create, {:freecen1_vld_file => valid_attributes}, valid_session
        response.should redirect_to(Freecen1VldFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved freecen1_vld_file as @freecen1_vld_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        Freecen1VldFile.any_instance.stub(:save).and_return(false)
        post :create, {:freecen1_vld_file => { "file_name" => "invalid value" }}, valid_session
        assigns(:freecen1_vld_file).should be_a_new(Freecen1VldFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Freecen1VldFile.any_instance.stub(:save).and_return(false)
        post :create, {:freecen1_vld_file => { "file_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested freecen1_vld_file" do
        freecen1_vld_file = Freecen1VldFile.create! valid_attributes
        # Assuming there are no other freecen1_vld_files in the database, this
        # specifies that the Freecen1VldFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Freecen1VldFile.any_instance.should_receive(:update_attributes).with({ "file_name" => "MyString" })
        put :update, {:id => freecen1_vld_file.to_param, :freecen1_vld_file => { "file_name" => "MyString" }}, valid_session
      end

      it "assigns the requested freecen1_vld_file as @freecen1_vld_file" do
        freecen1_vld_file = Freecen1VldFile.create! valid_attributes
        put :update, {:id => freecen1_vld_file.to_param, :freecen1_vld_file => valid_attributes}, valid_session
        assigns(:freecen1_vld_file).should eq(freecen1_vld_file)
      end

      it "redirects to the freecen1_vld_file" do
        freecen1_vld_file = Freecen1VldFile.create! valid_attributes
        put :update, {:id => freecen1_vld_file.to_param, :freecen1_vld_file => valid_attributes}, valid_session
        response.should redirect_to(freecen1_vld_file)
      end
    end

    describe "with invalid params" do
      it "assigns the freecen1_vld_file as @freecen1_vld_file" do
        freecen1_vld_file = Freecen1VldFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Freecen1VldFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => freecen1_vld_file.to_param, :freecen1_vld_file => { "file_name" => "invalid value" }}, valid_session
        assigns(:freecen1_vld_file).should eq(freecen1_vld_file)
      end

      it "re-renders the 'edit' template" do
        freecen1_vld_file = Freecen1VldFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Freecen1VldFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => freecen1_vld_file.to_param, :freecen1_vld_file => { "file_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested freecen1_vld_file" do
      freecen1_vld_file = Freecen1VldFile.create! valid_attributes
      expect {
        delete :destroy, {:id => freecen1_vld_file.to_param}, valid_session
      }.to change(Freecen1VldFile, :count).by(-1)
    end

    it "redirects to the freecen1_vld_files list" do
      freecen1_vld_file = Freecen1VldFile.create! valid_attributes
      delete :destroy, {:id => freecen1_vld_file.to_param}, valid_session
      response.should redirect_to(freecen1_vld_files_url)
    end
  end

end
