require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FreeregContentsController do

  # This should return the minimal set of attributes required to create a valid
  # FreeregContent. As you add validations to FreeregContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FreeregContentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all freereg_contents as @freereg_contents" do
      freereg_content = FreeregContent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:freereg_contents).should eq([freereg_content])
    end
  end

  describe "GET show" do
    it "assigns the requested freereg_content as @freereg_content" do
      freereg_content = FreeregContent.create! valid_attributes
      get :show, {:id => freereg_content.to_param}, valid_session
      assigns(:freereg_content).should eq(freereg_content)
    end
  end

  describe "GET new" do
    it "assigns a new freereg_content as @freereg_content" do
      get :new, {}, valid_session
      assigns(:freereg_content).should be_a_new(FreeregContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested freereg_content as @freereg_content" do
      freereg_content = FreeregContent.create! valid_attributes
      get :edit, {:id => freereg_content.to_param}, valid_session
      assigns(:freereg_content).should eq(freereg_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FreeregContent" do
        expect {
          post :create, {:freereg_content => valid_attributes}, valid_session
        }.to change(FreeregContent, :count).by(1)
      end

      it "assigns a newly created freereg_content as @freereg_content" do
        post :create, {:freereg_content => valid_attributes}, valid_session
        assigns(:freereg_content).should be_a(FreeregContent)
        assigns(:freereg_content).should be_persisted
      end

      it "redirects to the created freereg_content" do
        post :create, {:freereg_content => valid_attributes}, valid_session
        response.should redirect_to(FreeregContent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved freereg_content as @freereg_content" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreeregContent.any_instance.stub(:save).and_return(false)
        post :create, {:freereg_content => {  }}, valid_session
        assigns(:freereg_content).should be_a_new(FreeregContent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreeregContent.any_instance.stub(:save).and_return(false)
        post :create, {:freereg_content => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested freereg_content" do
        freereg_content = FreeregContent.create! valid_attributes
        # Assuming there are no other freereg_contents in the database, this
        # specifies that the FreeregContent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FreeregContent.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => freereg_content.to_param, :freereg_content => { "these" => "params" }}, valid_session
      end

      it "assigns the requested freereg_content as @freereg_content" do
        freereg_content = FreeregContent.create! valid_attributes
        put :update, {:id => freereg_content.to_param, :freereg_content => valid_attributes}, valid_session
        assigns(:freereg_content).should eq(freereg_content)
      end

      it "redirects to the freereg_content" do
        freereg_content = FreeregContent.create! valid_attributes
        put :update, {:id => freereg_content.to_param, :freereg_content => valid_attributes}, valid_session
        response.should redirect_to(freereg_content)
      end
    end

    describe "with invalid params" do
      it "assigns the freereg_content as @freereg_content" do
        freereg_content = FreeregContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreeregContent.any_instance.stub(:save).and_return(false)
        put :update, {:id => freereg_content.to_param, :freereg_content => {  }}, valid_session
        assigns(:freereg_content).should eq(freereg_content)
      end

      it "re-renders the 'edit' template" do
        freereg_content = FreeregContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreeregContent.any_instance.stub(:save).and_return(false)
        put :update, {:id => freereg_content.to_param, :freereg_content => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested freereg_content" do
      freereg_content = FreeregContent.create! valid_attributes
      expect {
        delete :destroy, {:id => freereg_content.to_param}, valid_session
      }.to change(FreeregContent, :count).by(-1)
    end

    it "redirects to the freereg_contents list" do
      freereg_content = FreeregContent.create! valid_attributes
      delete :destroy, {:id => freereg_content.to_param}, valid_session
      response.should redirect_to(freereg_contents_url)
    end
  end

end
